spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: zbh080931
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**

server:
  port: @server.port@
  servlet:
    context-path: /

mybatis:
  type-aliases-package: com.annotation.study.user.model
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true